# Generated by Django 4.2.3 on 2023-07-25 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_remove_post_follower_remove_post_following_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
